use_frameworks!

target 'RxSwifter_Example' do
  pod 'RxSwifter', :path => '../'
  pod 'Swifter', :git => 'git@github.com:mattdonnelly/Swifter.git'

  target 'RxSwifter_Tests' do
    inherit! :search_paths

    
  end
end
